### ISSUE TITLE
Configuration of languages supported

### ISSUE THREAD

**Issue by danschultzer** [danschultzer/blazing-bookkeeper#17]
Tesseract [has a huge selection](https://github.com/tesseract-ocr/tessdata) of trained data for most languages. In total, there's 1.5 GB of data. By default, we're just installing English and orientation trained data. There're a few ways we can make this easy for the user:
- Add a Preferences window where they can download the language they want support for
- Automatically detect language on platform and prompt if user wants support for said language

This might go hand-in-hand with i18n, which is something we haven't looked at yet.

**Comment by danschultzer** [comment]
We should try to test with non-English receipts to see how well the English trained data works. It might not be necessary to add options for languages just yet.

**Comment by Schultzer** [comment]
I'm closing this for now as we decided only to support English.
